[package]
name = "punter"
version = "0.1.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]

[lib]
name = "punter"
path = "src/lib.rs"

[dependencies]

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
